enum WLAudioPlayerEvent {
    WL_WORKLET_NODE_OPEN_REQ,
    WL_WORKLET_NODE_OPEN_RSP,
    WL_WORKLET_NODE_CLOSE_REQ,
    WL_WORKLET_NODE_CLOSE_RSP,
    WL_WORKLET_NODE_START_REQ,
    WL_WORKLET_NODE_START_RSP,
    WL_WORKLET_NODE_STOP_REQ,
    WL_WORKLET_NODE_STOP_RSP,
    WL_WORKLET_NODE_PAUSE_REQ,
    WL_WORKLET_NODE_PAUSE_RSP,
    WL_WORKLET_NODE_RESUME_REQ,
    WL_WORKLET_NODE_RESUME_RSP,
    WL_WORKLET_NODE_PUT_DATA,
    WL_WORKLET_NODE_END_DATA,
    WL_WORKLET_NODE_CLEAR_CUR,
    WL_WORKLET_NODE_FINISH_PLAY
}

enum WLAudioRecorderEvent {
    WL_WORKLET_NODE_OPEN_REQ,
    WL_WORKLET_NODE_OPEN_RSP,
    WL_WORKLET_NODE_CLOSE_REQ,
    WL_WORKLET_NODE_CLOSE_RSP,
    WL_WORKLET_NODE_START_REQ,
    WL_WORKLET_NODE_START_RSP,
    WL_WORKLET_NODE_STOP_REQ,
    WL_WORKLET_NODE_STOP_RSP,
    WL_WORKLET_NODE_DATA_IND
}

enum WLAudioEvent {
    WL_AUDIO_FINISH_PLAY_IND,
    WL_AUDIO_OPUS_CODED_DATA_IND
}

enum WLPlayerType {
    WL_PTT_STREAM_PLAYER,
    WL_PTT_HISTORY_PLAYER,
    WL_PTT_SINGLE_PLAYER,
    WL_PTT_PLAYER_NUM
}

export {WLAudioPlayerEvent, WLAudioRecorderEvent, WLAudioEvent, WLPlayerType}
